// examples/react-router-framework/app/routes/account.tsx
import { useOidc, enforceLogin } from "../oidc.client";
import { parseKeycloakIssuerUri } from "oidc-spa/tools/parseKeycloakIssuerUri";
import type { Route } from "./+types/account";

export async function clientLoader({ request }: Route.ClientLoaderArgs) {
    await enforceLogin(request);
}

export function HydrateFallback() {
    return <div>Loading...</div>;
}

export default function Account() {
    const {
        goToAuthServer,
        backFromAuthServer,
        params: { issuerUri, clientId }
    } = useOidc({ assert: "user logged in" });

    const keycloak = parseKeycloakIssuerUri(issuerUri);

    if (keycloak === undefined) {
        throw new Error("We expect Keycloak to be the OIDC provider of this App");
    }

    return (
        <div>
            <h1>Account</h1>
            <p>
                <a
                    href={keycloak.getAccountUrl({
                        clientId,
                        backToAppFromAccountUrl: location.href,
                        locale: "en"
                    })}
                >
                    Go to Keycloak Account Management Page
                </a>
            </p>
            <p>
                <button
                    onClick={() =>
                        goToAuthServer({
                            extraQueryParams: {
                                kc_action: "CHANGE_PASSWORD"
                            }
                        })
                    }
                >
                    Change My Password
                </button>
                {backFromAuthServer?.extraQueryParams.kc_action === "CHANGE_PASSWORD" && (
                    <span>
                        {backFromAuthServer.result.kc_action_status === "success"
                            ? "Password Updated!"
                            : "Password unchanged"}
                    </span>
                )}
            </p>
            <p>
                <button
                    onClick={() =>
                        goToAuthServer({
                            extraQueryParams: {
                                kc_action: "UPDATE_PROFILE"
                            }
                        })
                    }
                >
                    Update My Profile Information
                </button>
                {backFromAuthServer?.extraQueryParams.kc_action === "UPDATE_PROFILE" && (
                    <span>
                        {backFromAuthServer.result.kc_action_status === "success"
                            ? "Profile Updated!"
                            : "Profile unchanged"}
                    </span>
                )}
            </p>
            <p>
                <button
                    onClick={() =>
                        goToAuthServer({
                            extraQueryParams: {
                                kc_action: "delete_account"
                            }
                        })
                    }
                >
                    Delete My Account
                </button>
            </p>
        </div>
    );
}

// examples/angular/src/app/pages/account.ts
import { Component, inject } from '@angular/core';
import { createKeycloakUtils, isKeycloak } from 'oidc-spa/keycloak';
import { Oidc } from '../services/oidc.service';

type AccountAction = 'UPDATE_PASSWORD' | 'UPDATE_PROFILE' | 'delete_account';

@Component({
  selector: 'app-account',
  template: `
    <h1>Your account</h1>

    <dl>
      <div>
        <dt>Name</dt>
        <dd>{{ oidc.$decodedIdToken().name }}</dd>
      </div>
      @if (oidc.$decodedIdToken().email) {
      <div>
        <dt>Email</dt>
        <dd>{{ oidc.$decodedIdToken().email }}</dd>
      </div>
      } @if (oidc.$decodedIdToken().preferred_username) {
      <div>
        <dt>Username</dt>
        <dd>{{ oidc.$decodedIdToken().preferred_username }}</dd>
      </div>
      }
    </dl>

    @if (keycloakUtils) {
    <section>
      <p>Account management actions:</p>
      <div>
        <button (click)="triggerAccountAction('UPDATE_PASSWORD')">Change password</button>
        <button (click)="triggerAccountAction('UPDATE_PROFILE')">Update profile</button>
        <button (click)="triggerAccountAction('delete_account')">Delete account</button>
      </div>

      @if (actionResult) {
      <p>
        Result for {{ actionResult.action }}:
        <strong>{{ actionResult.status }}</strong>
      </p>
      } @if (accountUrl) {
      <p>
        <a [href]="accountUrl" rel="noreferrer">Open Keycloak account console</a>
      </p>
      }
    </section>
    }
  `,
})
export class Account {
  oidc = inject(Oidc);

  protected readonly keycloakUtils = isKeycloak({ issuerUri: this.oidc.issuerUri })
    ? createKeycloakUtils({ issuerUri: this.oidc.issuerUri })
    : undefined;

  protected readonly accountUrl = this.keycloakUtils?.getAccountUrl({
    clientId: this.oidc.clientId,
    validRedirectUri: this.oidc.validRedirectUri,
    locale: undefined,
  });

  protected readonly actionResult = this.readAccountActionResult();

  protected triggerAccountAction(action: AccountAction) {
    return this.oidc.goToAuthServer({
      extraQueryParams: { kc_action: action },
    });
  }

  private readAccountActionResult(): { action: string; status: string } | undefined {
    const searchParams = new URLSearchParams(window.location.search);

    const action = searchParams.get('kc_action');
    const status = searchParams.get('kc_action_status');

    if (action === null || status === null) {
      return undefined;
    }

    return { action, status };
  }
}
