// examples/react-router-declarative/src/pages/AdminOnly.tsx
import { createKeycloakUtils, isKeycloak } from "oidc-spa/keycloak";
import { useOidc, withLoginEnforced } from "~/oidc";

const REQUIRED_ROLE = "realm-admin";

const AdminOnly = withLoginEnforced(() => {
    const { decodedIdToken, issuerUri } = useOidc({ assert: "user logged in" });

    const keycloakUtils = isKeycloak({ issuerUri }) ? createKeycloakUtils({ issuerUri }) : undefined;

    if (!decodedIdToken.realm_access?.roles.includes(REQUIRED_ROLE)) {
        return (
            <section className="rounded-xl border border-rose-500/40 bg-rose-950/30 p-4 text-sm text-rose-100">
                <p>
                    You need the <code>{REQUIRED_ROLE}</code> role to view this page.
                </p>
            </section>
        );
    }

    return (
        <section className="space-y-6">
            <div className="space-y-1">
                <h1 className="text-xl font-semibold text-white">Administration Page</h1>
                <p className="text-sm text-slate-300">
                    Access is granted because your ID token includes the <code>{REQUIRED_ROLE}</code>{" "}
                    role.
                </p>
            </div>

            {keycloakUtils !== undefined && (
                <div className="rounded-xl border border-slate-800 bg-slate-900 p-4 text-sm text-slate-300">
                    <a
                        className="inline-flex items-center text-slate-200 underline decoration-slate-700 underline-offset-4 transition-colors hover:decoration-slate-400"
                        href={keycloakUtils.adminConsoleUrl}
                        target="_blank"
                        rel="noreferrer"
                    >
                        Open the Keycloak administration console
                    </a>
                </div>
            )}
        </section>
    );
});

export default AdminOnly;

// examples/nuxt-spa/app/pages/admin-only.vue
<script setup lang="ts">
import { createKeycloakUtils, isKeycloak } from "oidc-spa/keycloak";

// TODO DAN: Roles
definePageMeta({
    middleware: "auth"
});

const REQUIRED_ROLE = "realm-admin";

const { idToken, issuerUri } = useAuth();

// TODO DAN: move this logic to a composable since it's needed in multiple places
const keycloakUtils = computed(() => {
    if (!isKeycloak({ issuerUri: issuerUri.value })) {
        return undefined;
    }

    return createKeycloakUtils({ issuerUri: issuerUri.value });
});

const hasRequiredRole = computed(() => {
    return !!idToken.value?.realm_access?.roles.includes(REQUIRED_ROLE);
});
</script>

<template>
    <section v-if="!hasRequiredRole">
        <UAlert
            color="error"
            variant="soft"
            icon="i-lucide-shield-x"
            title="Access denied"
            :description="`You need the ${REQUIRED_ROLE} role to view this page.`"
        />
    </section>

    <section v-else class="space-y-6">
        <UCard variant="subtle">
            <template #header>
                <h1 class="text-xl font-semibold">Administration Page</h1>
            </template>

            <UAlert
                color="success"
                variant="soft"
                icon="i-lucide-shield-check"
                :description="`Access is granted because your ID token includes the ${REQUIRED_ROLE} role.`"
            />

            <template #footer>
                <UButton
                    v-if="keycloakUtils"
                    color="neutral"
                    variant="outline"
                    icon="i-lucide-square-arrow-out-up-right"
                    :to="keycloakUtils.adminConsoleUrl"
                    target="_blank"
                >
                    Open the Keycloak administration console
                </UButton>
            </template>
        </UCard>
    </section>
</template>
