// examples/nuxt-spa/app/pages/protected.vue
<script setup lang="ts">
import { createKeycloakUtils, isKeycloak } from "oidc-spa/keycloak";

definePageMeta({
    middleware: "auth"
});

type DemoPost = {
    id: number;
    title: string;
    body: string;
};

const {
    idToken,
    issuerUri,
    clientId,
    validRedirectUri,
    goToAuthServer,
    backFromAuthServer,
    fetchWithAuth
} = useAuth();

const keycloakUtils = computed(() => {
    if (!isKeycloak({ issuerUri: issuerUri.value })) {
        return undefined;
    }

    return createKeycloakUtils({ issuerUri: issuerUri.value });
});

// TODO DAN: useAsyncData
const demoPosts = ref<DemoPost[] | undefined>(undefined);

onMounted(async () => {
    const response = await fetchWithAuth("https://jsonplaceholder.typicode.com/posts?_limit=4");
    demoPosts.value = await response.json();
});
</script>

<template>
    <section class="space-y-6">
        <UCard variant="subtle">
            <template #header>
                <div
                    class="flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between"
                >
                    <div>
                        <p class="text-xs uppercase tracking-wide text-muted">Protected content</p>
                        <h1 class="text-2xl font-semibold">Hello {{ idToken?.name ?? "user" }}</h1>
                    </div>
                    <UBadge color="primary" variant="soft">Authenticated</UBadge>
                </div>
            </template>

            <p class="text-sm text-toned">
                These actions come directly from your identity provider via oidc-spa.
            </p>

            <dl class="mt-4 grid gap-2 text-sm">
                <div class="flex flex-wrap justify-between gap-2">
                    <dt class="text-muted">Subject</dt>
                    <dd class="font-medium">{{ idToken?.sub }}</dd>
                </div>
                <div v-if="idToken?.email" class="flex flex-wrap justify-between gap-2">
                    <dt class="text-muted">Email</dt>
                    <dd class="font-medium">{{ idToken.email }}</dd>
                </div>
                <div v-if="idToken?.preferred_username" class="flex flex-wrap justify-between gap-2">
                    <dt class="text-muted">Username</dt>
                    <dd class="font-medium">{{ idToken.preferred_username }}</dd>
                </div>
            </dl>

            <template #footer>
                <div class="space-y-3">
                    <div v-if="keycloakUtils" class="flex flex-wrap gap-2">
                        <UButton
                            class="w-full sm:w-auto"
                            color="neutral"
                            variant="soft"
                            icon="i-lucide-key-round"
                            @click="
                                goToAuthServer({ extraQueryParams: { kc_action: 'UPDATE_PASSWORD' } })
                            "
                        >
                            Change password
                        </UButton>
                        <UButton
                            class="w-full sm:w-auto"
                            color="neutral"
                            variant="soft"
                            icon="i-lucide-user-round-cog"
                            @click="
                                goToAuthServer({ extraQueryParams: { kc_action: 'UPDATE_PROFILE' } })
                            "
                        >
                            Update profile
                        </UButton>
                        <UButton
                            class="w-full sm:w-auto"
                            color="error"
                            variant="soft"
                            icon="i-lucide-user-round-x"
                            @click="
                                goToAuthServer({ extraQueryParams: { kc_action: 'delete_account' } })
                            "
                        >
                            Delete account
                        </UButton>
                        <UButton
                            class="w-full sm:w-auto"
                            color="neutral"
                            variant="outline"
                            icon="i-lucide-square-arrow-out-up-right"
                            :to="
                                keycloakUtils.getAccountUrl({
                                    clientId,
                                    validRedirectUri,
                                    locale: undefined
                                })
                            "
                            target="_blank"
                        >
                            My Account
                        </UButton>
                    </div>

                    <UAlert
                        v-if="backFromAuthServer?.extraQueryParams.kc_action"
                        color="primary"
                        variant="soft"
                        icon="i-lucide-arrow-left-right"
                        :title="`Result for ${backFromAuthServer.extraQueryParams.kc_action}`"
                        :description="backFromAuthServer.result.kc_action_status"
                    />
                </div>
            </template>
        </UCard>

        <UCard variant="outline">
            <template #header>
                <h2 class="text-lg font-semibold">Authenticated API example</h2>
            </template>

            <UAlert
                color="neutral"
                variant="subtle"
                icon="i-lucide-info"
                title="fetchWithAuth"
                description="Requests include Authorization: Bearer <access_token> when logged in."
            />

            <p v-if="!demoPosts" class="mt-4 text-sm text-toned">Loading example posts…</p>

            <div v-else class="mt-4 space-y-3">
                <UCard v-for="post in demoPosts" :key="post.id" variant="soft">
                    <h3 class="text-sm font-semibold">{{ post.title }}</h3>
                    <p class="mt-1 text-sm text-toned">{{ post.body }}</p>
                </UCard>
            </div>
        </UCard>
    </section>
</template>

// examples/react-router-data/src/pages/Protected.tsx
import type { ReactNode } from "react";
import { useLoaderData } from "react-router";
import { useOidc, enforceLogin, fetchWithAuth } from "~/oidc";
import { isKeycloak, createKeycloakUtils } from "oidc-spa/keycloak";

type DemoPost = { id: number; title: string; body: string };

export async function loader(args: {
    request?: { url?: string };
    cause?: "preload" | string;
    location?: { href?: string };
}) {
    // Ensure only logged-in users access this route; redirect to IdP if needed.
    await enforceLogin(args);

    const demoPosts: DemoPost[] = await fetchWithAuth(
        "https://jsonplaceholder.typicode.com/posts?_limit=4"
    ).then(r => r.json());

    return { demoPosts } as const;
}

export default function Protected() {
    // Safe to assume user is logged in here.
    const { decodedIdToken, goToAuthServer, backFromAuthServer, issuerUri, clientId, validRedirectUri } =
        useOidc({
            assert: "user logged in"
        });

    const keycloakUtils = isKeycloak({ issuerUri }) ? createKeycloakUtils({ issuerUri }) : undefined;

    const { demoPosts } = useLoaderData() as { demoPosts: DemoPost[] };

    return (
        <section className="space-y-6">
            <div className="space-y-1">
                <p className="text-sm uppercase tracking-wide text-slate-400">Protected content</p>
                <h1 className="text-2xl font-semibold text-white">Hello {decodedIdToken.name}</h1>
                <p className="text-base text-slate-300">
                    These actions come directly from your identity provider via oidc-spa.
                </p>
            </div>

            <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 shadow-sm shadow-slate-950/40">
                <dl className="grid gap-2 text-sm text-slate-400">
                    <InfoRow label="Subject">{decodedIdToken.sub}</InfoRow>
                    {decodedIdToken.email && <InfoRow label="Email">{decodedIdToken.email}</InfoRow>}
                    {decodedIdToken.preferred_username && (
                        <InfoRow label="Username">{decodedIdToken.preferred_username}</InfoRow>
                    )}
                </dl>

                {keycloakUtils && (
                    <>
                        <div className="mt-6 flex flex-wrap gap-3">
                            <button
                                className="inline-flex items-center rounded-full border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-200 transition-colors hover:border-slate-500"
                                onClick={() =>
                                    goToAuthServer({
                                        extraQueryParams: { kc_action: "UPDATE_PASSWORD" }
                                    })
                                }
                            >
                                Change password
                            </button>
                            <button
                                className="inline-flex items-center rounded-full border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-200 transition-colors hover:border-slate-500"
                                onClick={() =>
                                    goToAuthServer({
                                        extraQueryParams: { kc_action: "UPDATE_PROFILE" }
                                    })
                                }
                            >
                                Update profile
                            </button>
                            <button
                                className="inline-flex items-center rounded-full border border-rose-400/60 px-4 py-2 text-sm font-semibold text-rose-200 transition-colors hover:border-rose-300 hover:text-rose-100"
                                onClick={() =>
                                    goToAuthServer({
                                        extraQueryParams: { kc_action: "delete_account" }
                                    })
                                }
                            >
                                Delete account
                            </button>
                            <a
                                className="group inline-flex items-center gap-2 rounded-full border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-200 transition-colors hover:border-slate-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-200/40 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-900"
                                href={keycloakUtils.getAccountUrl({
                                    clientId,
                                    validRedirectUri,
                                    locale: undefined
                                })}
                            >
                                My Account
                                <svg
                                    aria-hidden="true"
                                    className="h-3 w-3 text-slate-400 transition-colors group-hover:text-slate-200"
                                    viewBox="0 0 12 12"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        d="M4 2.5h5.5V8"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth="1.5"
                                    />
                                    <path
                                        d="M2.5 9.5 9.5 2.5"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth="1.5"
                                    />
                                </svg>
                            </a>
                        </div>

                        {backFromAuthServer?.extraQueryParams.kc_action && (
                            <p className="mt-4 text-sm text-slate-400">
                                Result for {backFromAuthServer.extraQueryParams.kc_action}:{" "}
                                <span className="font-medium text-white">
                                    {backFromAuthServer.result.kc_action_status}
                                </span>
                            </p>
                        )}
                    </>
                )}
            </div>

            <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 shadow-sm shadow-slate-950/40">
                <div className="space-y-2 text-sm text-slate-300">
                    <p>
                        The list below was fetched during the loader with{" "}
                        <code className="font-mono text-xs text-slate-200">fetchWithAuth</code>, which
                        automatically injects{" "}
                        <code className="font-mono text-xs text-slate-200">
                            Authorization: Bearer &lt;access_token&gt;
                        </code>{" "}
                        headers into every request.
                    </p>
                    <p className="text-slate-400">
                        JSONPlaceholder is a public API, we treat it as a stand-in for a protected
                        resource server.
                    </p>
                </div>
                <ul className="mt-4 space-y-3">
                    {demoPosts.map(post => (
                        <li
                            key={post.id}
                            className="rounded-xl border border-slate-800/80 bg-slate-950/50 p-4 shadow-inner shadow-black/20"
                        >
                            <p className="text-sm font-semibold text-white">{post.title}</p>
                            <p className="mt-1 text-sm text-slate-400">{post.body}</p>
                        </li>
                    ))}
                </ul>
            </div>
        </section>
    );
}

function InfoRow({ label, children }: { label: string; children: ReactNode }) {
    return (
        <div className="flex flex-wrap justify-between gap-2">
            <dt className="text-slate-400">{label}</dt>
            <dd className="font-medium text-white">{children}</dd>
        </div>
    );
}
