// examples/tanstack-router/src/pages/PublicPage.tsx
import reactLogo from "assets/react.svg";
import viteLogo from "assets/vite.svg";

export default function PublicPage() {
    return (
        <>
            <div>
                <a href="https://vitejs.dev" target="_blank">
                    <img src={viteLogo} className="logo" alt="Vite logo" />
                </a>
                <a href="https://react.dev" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>
            <h4>This is a page that do not requires the user to be authenticated</h4>
        </>
    );
}

// examples/svelte/src/pages/PublicPage.svelte
<script lang="ts">
    import svelteLogo from "../assets/svelte.svg";
    import viteLogo from "../assets/vite.svg";
</script>

<div>
    <a href="https://vitejs.dev" target="_blank">
        <img src={viteLogo} class="logo" alt="Vite logo" />
    </a>
    <a href="https://react.dev" target="_blank">
        <img src={svelteLogo} class="logo react" alt="React logo" />
    </a>
</div>
<h4>This is a page that do not requires the user to be authenticated</h4>
